// Built-in service templates with guides and OAuth support

export interface TemplateField {
  label: string;
  fieldType: 'TEXT' | 'SECRET' | 'URL';
  required: boolean;
  placeholder?: string;
  hint?: string;
  validationPattern?: string;
}

export interface TemplateGuideStep {
  text: string;
  textHe?: string;
  imageUrl?: string;
}

export interface ServiceTemplate {
  slug: string;
  name: string;
  nameHe: string;
  icon: string;
  category: string;
  authMethod: 'OAUTH' | 'MANUAL' | 'BOTH';
  oauthProvider?: string;
  oauthScopes?: string;
  fields: TemplateField[];
  guide: {
    en: TemplateGuideStep[];
    he: TemplateGuideStep[];
  };
}

export const BUILT_IN_TEMPLATES: ServiceTemplate[] = [
  {
    slug: 'facebook',
    name: 'Facebook',
    nameHe: 'פייסבוק',
    icon: 'facebook',
    category: 'social',
    authMethod: 'BOTH',
    oauthProvider: 'facebook',
    oauthScopes: 'pages_manage_posts,pages_read_engagement,pages_show_list',
    fields: [
      {
        label: 'App ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '123456789012345',
        hint: 'A 15-16 digit number',
        validationPattern: '^\\d{15,16}$',
      },
      {
        label: 'App Secret',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'abc123def456...',
        hint: 'A 32-character hex string',
        validationPattern: '^[a-f0-9]{32}$',
      },
      {
        label: 'Page Access Token',
        fieldType: 'SECRET',
        required: false,
        hint: 'Long token starting with EAA...',
        validationPattern: '^EAA',
      },
    ],
    guide: {
      en: [
        { text: 'Go to developers.facebook.com and log in' },
        { text: 'Click "My Apps" in the top right' },
        { text: 'Select your app (or create one)' },
        { text: 'Go to Settings → Basic' },
        { text: 'Copy the App ID and App Secret' },
      ],
      he: [
        { text: 'היכנסו ל-developers.facebook.com והתחברו' },
        { text: 'לחצו על "My Apps" בפינה הימנית העליונה' },
        { text: 'בחרו את האפליקציה שלכם (או צרו חדשה)' },
        { text: 'לכו ל-Settings → Basic' },
        { text: 'העתיקו את ה-App ID וה-App Secret' },
      ],
    },
  },
  {
    slug: 'google',
    name: 'Google',
    nameHe: 'גוגל',
    icon: 'chrome',
    category: 'analytics',
    authMethod: 'BOTH',
    oauthProvider: 'google',
    oauthScopes: 'https://www.googleapis.com/auth/analytics.readonly',
    fields: [
      {
        label: 'Client ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '123456789.apps.googleusercontent.com',
        hint: 'Ends with .apps.googleusercontent.com',
      },
      {
        label: 'Client Secret',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'GOCSPX-...',
        hint: 'Starts with GOCSPX-',
      },
    ],
    guide: {
      en: [
        { text: 'Go to console.cloud.google.com' },
        { text: 'Select your project' },
        { text: 'Go to APIs & Services → Credentials' },
        { text: 'Click on your OAuth 2.0 Client ID' },
        { text: 'Copy the Client ID and Client Secret' },
      ],
      he: [
        { text: 'היכנסו ל-console.cloud.google.com' },
        { text: 'בחרו את הפרויקט שלכם' },
        { text: 'לכו ל-APIs & Services → Credentials' },
        { text: 'לחצו על ה-OAuth 2.0 Client ID' },
        { text: 'העתיקו את ה-Client ID וה-Client Secret' },
      ],
    },
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    nameHe: 'אינסטגרם',
    icon: 'instagram',
    category: 'social',
    authMethod: 'OAUTH',
    oauthProvider: 'facebook',
    oauthScopes: 'instagram_basic,instagram_content_publish,pages_show_list',
    fields: [],
    guide: { en: [], he: [] },
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    nameHe: 'סטרייפ',
    icon: 'credit-card',
    category: 'payments',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Publishable Key',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'pk_live_...',
        hint: 'Starts with pk_live_ or pk_test_',
        validationPattern: '^pk_(live|test)_',
      },
      {
        label: 'Secret Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'sk_live_...',
        hint: 'Starts with sk_live_ or sk_test_',
        validationPattern: '^sk_(live|test)_',
      },
      {
        label: 'Webhook Secret',
        fieldType: 'SECRET',
        required: false,
        placeholder: 'whsec_...',
        hint: 'Starts with whsec_',
        validationPattern: '^whsec_',
      },
    ],
    guide: {
      en: [
        { text: 'Go to dashboard.stripe.com and log in' },
        { text: 'Click "Developers" in the top menu' },
        { text: 'Go to "API keys"' },
        { text: 'Copy the Publishable key and Secret key' },
        { text: 'For webhooks: go to Developers → Webhooks' },
      ],
      he: [
        { text: 'היכנסו ל-dashboard.stripe.com והתחברו' },
        { text: 'לחצו על "Developers" בתפריט העליון' },
        { text: 'לכו ל-"API keys"' },
        { text: 'העתיקו את ה-Publishable key וה-Secret key' },
        { text: 'לוובהוקס: לכו ל-Developers → Webhooks' },
      ],
    },
  },
  {
    slug: 'sendgrid',
    name: 'SendGrid',
    nameHe: 'סנדגריד',
    icon: 'mail',
    category: 'email',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'SG....',
        hint: 'Starts with SG.',
        validationPattern: '^SG\\.',
      },
    ],
    guide: {
      en: [
        { text: 'Go to app.sendgrid.com and log in' },
        { text: 'Go to Settings → API Keys' },
        { text: 'Click "Create API Key"' },
        { text: 'Give it a name and select permissions' },
        { text: 'Copy the key (you can only see it once!)' },
      ],
      he: [
        { text: 'היכנסו ל-app.sendgrid.com והתחברו' },
        { text: 'לכו ל-Settings → API Keys' },
        { text: 'לחצו על "Create API Key"' },
        { text: 'תנו שם ובחרו הרשאות' },
        { text: 'העתיקו את המפתח (ניתן לראות אותו רק פעם אחת!)' },
      ],
    },
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    nameHe: 'קלאודפלר',
    icon: 'cloud',
    category: 'hosting',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Token',
        fieldType: 'SECRET',
        required: true,
        hint: 'A long string of letters and numbers',
      },
      {
        label: 'Zone ID',
        fieldType: 'TEXT',
        required: false,
        placeholder: '023e105f4ecef8ad...',
        hint: 'Found on your domain overview page',
        validationPattern: '^[a-f0-9]{32}$',
      },
    ],
    guide: {
      en: [
        { text: 'Go to dash.cloudflare.com and log in' },
        { text: 'Click your profile icon → "My Profile"' },
        { text: 'Go to "API Tokens" tab' },
        { text: 'Click "Create Token" or copy an existing one' },
        { text: 'For Zone ID: go to your domain → Overview → right sidebar' },
      ],
      he: [
        { text: 'היכנסו ל-dash.cloudflare.com והתחברו' },
        { text: 'לחצו על אייקון הפרופיל → "My Profile"' },
        { text: 'לכו ללשונית "API Tokens"' },
        { text: 'לחצו "Create Token" או העתיקו קיים' },
        { text: 'ל-Zone ID: לכו לדומיין → Overview → סרגל צדדי ימני' },
      ],
    },
  },
  {
    slug: 'tiktok',
    name: 'TikTok Business',
    nameHe: 'טיקטוק עסקי',
    icon: 'music',
    category: 'social',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'App ID',
        fieldType: 'TEXT',
        required: true,
      },
      {
        label: 'App Secret',
        fieldType: 'SECRET',
        required: true,
      },
    ],
    guide: {
      en: [
        { text: 'Go to developers.tiktok.com' },
        { text: 'Click "My Apps"' },
        { text: 'Select your app' },
        { text: 'Find the App ID and App Secret on the app page' },
      ],
      he: [
        { text: 'היכנסו ל-developers.tiktok.com' },
        { text: 'לחצו על "My Apps"' },
        { text: 'בחרו את האפליקציה' },
        { text: 'מצאו את ה-App ID וה-App Secret בדף האפליקציה' },
      ],
    },
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    nameHe: 'מיילצ\'ימפ',
    icon: 'mail',
    category: 'email',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Key',
        fieldType: 'SECRET',
        required: true,
        hint: 'Ends with -usX (e.g., -us21)',
        validationPattern: '-us\\d+$',
      },
    ],
    guide: {
      en: [
        { text: 'Log in to Mailchimp' },
        { text: 'Click your profile icon → Account & billing' },
        { text: 'Go to Extras → API keys' },
        { text: 'Click "Create A Key"' },
        { text: 'Copy the generated key' },
      ],
      he: [
        { text: 'היכנסו למיילצ\'ימפ' },
        { text: 'לחצו על אייקון הפרופיל → Account & billing' },
        { text: 'לכו ל-Extras → API keys' },
        { text: 'לחצו "Create A Key"' },
        { text: 'העתיקו את המפתח שנוצר' },
      ],
    },
  },
  // --- PostPilot social media templates ---
  {
    slug: 'postpilot-instagram',
    name: 'Instagram Business API (PostPilot)',
    nameHe: 'אינסטגרם ביזנס API (פוסטפיילוט)',
    icon: 'instagram',
    category: 'social',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Client ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '123456789012345',
        hint: 'Facebook App ID (15-16 digit number)',
        validationPattern: '^\\d{15,16}$',
      },
      {
        label: 'Client Secret',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'abc123def456...',
        hint: 'Facebook App Secret (32-character hex string)',
        validationPattern: '^[a-f0-9]{32}$',
      },
      {
        label: 'Access Token',
        fieldType: 'SECRET',
        required: true,
        hint: 'Long-lived user access token starting with EAA...',
        validationPattern: '^EAA',
      },
    ],
    guide: {
      en: [
        { text: 'Go to developers.facebook.com and log in with the Facebook account linked to your Instagram Business profile' },
        { text: 'Click "My Apps" and select your app (or create a new one of type "Business")' },
        { text: 'Go to Settings -> Basic and copy the App ID (this is your Client ID) and App Secret (this is your Client Secret)' },
        { text: 'Add the "Instagram Graph API" and "Facebook Login" products to your app' },
        { text: 'In Facebook Login settings, add your redirect URI: https://your-domain.com/api/platforms/instagram/callback' },
        { text: 'Use the Graph API Explorer (developers.facebook.com/tools/explorer) to generate a User Access Token' },
        { text: 'Select permissions: instagram_basic, instagram_content_publish, instagram_manage_comments, instagram_manage_insights, pages_show_list, pages_read_engagement' },
        { text: 'Click "Generate Access Token" and authorize the app' },
        { text: 'Exchange the short-lived token for a long-lived one (valid 60 days) via the API or paste it here' },
      ],
      he: [
        { text: 'היכנסו ל-developers.facebook.com והתחברו עם חשבון הפייסבוק המקושר לפרופיל העסקי באינסטגרם' },
        { text: 'לחצו על "My Apps" ובחרו את האפליקציה (או צרו חדשה מסוג "Business")' },
        { text: 'לכו ל-Settings -> Basic והעתיקו את ה-App ID (זה ה-Client ID) וה-App Secret (זה ה-Client Secret)' },
        { text: 'הוסיפו את המוצרים "Instagram Graph API" ו-"Facebook Login" לאפליקציה' },
        { text: 'בהגדרות Facebook Login, הוסיפו את ה-redirect URI: https://your-domain.com/api/platforms/instagram/callback' },
        { text: 'השתמשו ב-Graph API Explorer (developers.facebook.com/tools/explorer) ליצירת User Access Token' },
        { text: 'בחרו הרשאות: instagram_basic, instagram_content_publish, instagram_manage_comments, instagram_manage_insights, pages_show_list, pages_read_engagement' },
        { text: 'לחצו "Generate Access Token" ואשרו את האפליקציה' },
        { text: 'המירו את הטוקן הקצר לטוקן ארוך-טווח (תקף 60 יום) דרך ה-API או הדביקו אותו כאן' },
      ],
    },
  },
  {
    slug: 'postpilot-tiktok',
    name: 'TikTok for Business (PostPilot)',
    nameHe: 'טיקטוק לעסקים (פוסטפיילוט)',
    icon: 'music',
    category: 'social',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'App ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '7123456789012345678',
        hint: 'Also called "Client Key" in the TikTok developer portal',
      },
      {
        label: 'App Secret',
        fieldType: 'SECRET',
        required: true,
        hint: 'Also called "Client Secret" in the TikTok developer portal',
      },
    ],
    guide: {
      en: [
        { text: 'Go to developers.tiktok.com and log in with your TikTok account' },
        { text: 'Click "Manage apps" in the top navigation' },
        { text: 'Click "Connect an app" or select an existing app' },
        { text: 'Choose app type "Web" and fill in app details' },
        { text: 'Under "Add products", enable "Login Kit" and "Content Posting API"' },
        { text: 'Set the redirect URI to: https://your-domain.com/api/platforms/tiktok/callback' },
        { text: 'Add required scopes: user.info.basic, video.publish, video.upload' },
        { text: 'Submit the app for review (sandbox mode works for testing)' },
        { text: 'Once approved, copy the "Client key" (App ID) and "Client secret" (App Secret) from the app details page' },
      ],
      he: [
        { text: 'היכנסו ל-developers.tiktok.com והתחברו עם חשבון הטיקטוק שלכם' },
        { text: 'לחצו על "Manage apps" בניווט העליון' },
        { text: 'לחצו "Connect an app" או בחרו אפליקציה קיימת' },
        { text: 'בחרו סוג אפליקציה "Web" ומלאו את פרטי האפליקציה' },
        { text: 'תחת "Add products", הפעילו "Login Kit" ו-"Content Posting API"' },
        { text: 'הגדירו את ה-redirect URI: https://your-domain.com/api/platforms/tiktok/callback' },
        { text: 'הוסיפו הרשאות נדרשות: user.info.basic, video.publish, video.upload' },
        { text: 'שלחו את האפליקציה לבדיקה (מצב sandbox עובד לבדיקות)' },
        { text: 'לאחר אישור, העתיקו את ה-"Client key" (App ID) וה-"Client secret" (App Secret) מדף פרטי האפליקציה' },
      ],
    },
  },
  {
    slug: 'postpilot-facebook-pages',
    name: 'Facebook Pages API (PostPilot)',
    nameHe: 'פייסבוק דפים API (פוסטפיילוט)',
    icon: 'facebook',
    category: 'social',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'App ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '123456789012345',
        hint: 'Facebook App ID (15-16 digit number)',
        validationPattern: '^\\d{15,16}$',
      },
      {
        label: 'App Secret',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'abc123def456...',
        hint: 'Facebook App Secret (32-character hex string)',
        validationPattern: '^[a-f0-9]{32}$',
      },
      {
        label: 'Page Access Token',
        fieldType: 'SECRET',
        required: true,
        hint: 'Long-lived Page Access Token starting with EAA...',
        validationPattern: '^EAA',
      },
    ],
    guide: {
      en: [
        { text: 'Go to developers.facebook.com and log in' },
        { text: 'Click "My Apps" and select your app (or create a new one of type "Business")' },
        { text: 'Go to Settings -> Basic and copy the App ID and App Secret' },
        { text: 'Add the "Facebook Login" product and set the redirect URI to: https://your-domain.com/api/platforms/facebook/callback' },
        { text: 'Use the Graph API Explorer (developers.facebook.com/tools/explorer) to generate a User Access Token' },
        { text: 'Select permissions: pages_manage_posts, pages_read_engagement, pages_show_list, pages_manage_metadata, publish_video' },
        { text: 'Click "Generate Access Token" and authorize' },
        { text: 'Exchange for a long-lived user token, then request your Page Access Token via: GET /me/accounts?access_token={long-lived-token}' },
        { text: 'Copy the Page Access Token from the response (it is already long-lived when derived from a long-lived user token)' },
      ],
      he: [
        { text: 'היכנסו ל-developers.facebook.com והתחברו' },
        { text: 'לחצו על "My Apps" ובחרו את האפליקציה (או צרו חדשה מסוג "Business")' },
        { text: 'לכו ל-Settings -> Basic והעתיקו את ה-App ID וה-App Secret' },
        { text: 'הוסיפו את המוצר "Facebook Login" והגדירו redirect URI: https://your-domain.com/api/platforms/facebook/callback' },
        { text: 'השתמשו ב-Graph API Explorer (developers.facebook.com/tools/explorer) ליצירת User Access Token' },
        { text: 'בחרו הרשאות: pages_manage_posts, pages_read_engagement, pages_show_list, pages_manage_metadata, publish_video' },
        { text: 'לחצו "Generate Access Token" ואשרו' },
        { text: 'המירו לטוקן ארוך-טווח, ואז בקשו Page Access Token דרך: GET /me/accounts?access_token={long-lived-token}' },
        { text: 'העתיקו את ה-Page Access Token מהתשובה (הוא כבר ארוך-טווח כשנגזר מטוקן משתמש ארוך-טווח)' },
      ],
    },
  },
  // --- Additional templates ---
  {
    slug: 'sentry',
    name: 'Sentry',
    nameHe: 'סנטרי',
    icon: 'bug',
    category: 'monitoring',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'DSN',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'https://abc123@o123.ingest.sentry.io/456',
        hint: 'Full DSN URL from project settings',
        validationPattern: '^https://',
      },
      {
        label: 'Auth Token',
        fieldType: 'SECRET',
        required: false,
        placeholder: 'sntrys_...',
        hint: 'For API access — starts with sntrys_',
        validationPattern: '^sntrys_',
      },
    ],
    guide: {
      en: [
        { text: 'Go to sentry.io and log in' },
        { text: 'Select your project (or create one)' },
        { text: 'Go to Settings → Projects → [Your Project]' },
        { text: 'Under "Client Keys (DSN)", copy the DSN' },
        { text: 'For Auth Token: Settings → Auth Tokens → Create' },
      ],
      he: [
        { text: 'היכנסו ל-sentry.io והתחברו' },
        { text: 'בחרו את הפרויקט (או צרו חדש)' },
        { text: 'לכו ל-Settings → Projects → [הפרויקט שלכם]' },
        { text: 'תחת "Client Keys (DSN)", העתיקו את ה-DSN' },
        { text: 'לטוקן: Settings → Auth Tokens → Create' },
      ],
    },
  },
  {
    slug: 'mixpanel',
    name: 'Mixpanel',
    nameHe: 'מיקספאנל',
    icon: 'bar-chart',
    category: 'analytics',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Project Token',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'abc123def456...',
        hint: '32-character hex token',
        validationPattern: '^[a-f0-9]{32}$',
      },
      {
        label: 'API Secret',
        fieldType: 'SECRET',
        required: false,
        hint: 'For server-side API access',
      },
    ],
    guide: {
      en: [
        { text: 'Go to mixpanel.com and log in' },
        { text: 'Click the gear icon → Project Settings' },
        { text: 'Copy the "Project Token"' },
        { text: 'For API Secret: go to "Access Keys" section' },
      ],
      he: [
        { text: 'היכנסו ל-mixpanel.com והתחברו' },
        { text: 'לחצו על אייקון הגלגל → Project Settings' },
        { text: 'העתיקו את ה-"Project Token"' },
        { text: 'ל-API Secret: לכו לחלק "Access Keys"' },
      ],
    },
  },
  {
    slug: 'revenuecat',
    name: 'RevenueCat',
    nameHe: 'רבניוקט',
    icon: 'dollar-sign',
    category: 'payments',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Public API Key',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'appl_...',
        hint: 'Starts with appl_ (Apple) or goog_ (Google)',
        validationPattern: '^(appl|goog)_',
      },
      {
        label: 'Secret API Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'sk_...',
        hint: 'Starts with sk_',
        validationPattern: '^sk_',
      },
    ],
    guide: {
      en: [
        { text: 'Go to app.revenuecat.com and log in' },
        { text: 'Select your project' },
        { text: 'Go to API Keys in the left sidebar' },
        { text: 'Copy the Public and Secret API keys' },
      ],
      he: [
        { text: 'היכנסו ל-app.revenuecat.com והתחברו' },
        { text: 'בחרו את הפרויקט' },
        { text: 'לכו ל-API Keys בסרגל הצדדי' },
        { text: 'העתיקו את מפתחות ה-Public וה-Secret' },
      ],
    },
  },
  {
    slug: 'apple-developer',
    name: 'Apple Developer',
    nameHe: 'אפל דולופר',
    icon: 'smartphone',
    category: 'mobile',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Team ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'ABC123DEF4',
        hint: '10-character alphanumeric',
        validationPattern: '^[A-Z0-9]{10}$',
      },
      {
        label: 'Key ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'ABC123DEF4',
        hint: '10-character alphanumeric',
        validationPattern: '^[A-Z0-9]{10}$',
      },
      {
        label: 'Private Key (.p8)',
        fieldType: 'SECRET',
        required: true,
        hint: 'The contents of the .p8 file starting with -----BEGIN PRIVATE KEY-----',
        validationPattern: '^-----BEGIN',
      },
      {
        label: 'Bundle ID',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'com.company.app',
        hint: 'Your app bundle identifier',
      },
    ],
    guide: {
      en: [
        { text: 'Go to developer.apple.com and log in' },
        { text: 'Go to "Certificates, Identifiers & Profiles"' },
        { text: 'For Team ID: look in the top right or Membership page' },
        { text: 'Go to Keys → create a new key' },
        { text: 'Download the .p8 file (only once!) and note the Key ID' },
        { text: 'Open the .p8 file with a text editor and copy its contents' },
      ],
      he: [
        { text: 'היכנסו ל-developer.apple.com והתחברו' },
        { text: 'לכו ל-"Certificates, Identifiers & Profiles"' },
        { text: 'ל-Team ID: הסתכלו בפינה הימנית או בדף Membership' },
        { text: 'לכו ל-Keys → צרו מפתח חדש' },
        { text: 'הורידו את קובץ ה-.p8 (פעם אחת בלבד!) ורשמו את ה-Key ID' },
        { text: 'פתחו את קובץ ה-.p8 עם עורך טקסט והעתיקו את התוכן' },
      ],
    },
  },
  {
    slug: 'google-play',
    name: 'Google Play Console',
    nameHe: 'גוגל פליי קונסול',
    icon: 'play',
    category: 'mobile',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Service Account JSON',
        fieldType: 'SECRET',
        required: true,
        hint: 'JSON key file contents from Google Cloud Console',
      },
      {
        label: 'Package Name',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'com.company.app',
        hint: 'Your Android app package name',
      },
    ],
    guide: {
      en: [
        { text: 'Go to play.google.com/console and log in' },
        { text: 'Go to Setup → API access' },
        { text: 'Create or link a Google Cloud project' },
        { text: 'Create a Service Account with appropriate permissions' },
        { text: 'Go to Google Cloud Console → IAM → Service Accounts' },
        { text: 'Click the service account → Keys → Add Key → JSON' },
        { text: 'Download the JSON file and paste its contents' },
      ],
      he: [
        { text: 'היכנסו ל-play.google.com/console והתחברו' },
        { text: 'לכו ל-Setup → API access' },
        { text: 'צרו או קשרו פרויקט Google Cloud' },
        { text: 'צרו Service Account עם הרשאות מתאימות' },
        { text: 'לכו ל-Google Cloud Console → IAM → Service Accounts' },
        { text: 'לחצו על ה-Service Account → Keys → Add Key → JSON' },
        { text: 'הורידו את קובץ ה-JSON והדביקו את תוכנו' },
      ],
    },
  },
  {
    slug: 'expo-eas',
    name: 'Expo / EAS',
    nameHe: 'אקספו / EAS',
    icon: 'terminal',
    category: 'mobile',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Access Token',
        fieldType: 'SECRET',
        required: true,
        hint: 'Personal access token from expo.dev',
      },
      {
        label: 'Project ID',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        hint: 'UUID from your project settings',
      },
    ],
    guide: {
      en: [
        { text: 'Go to expo.dev and log in' },
        { text: 'Click your avatar → Access Tokens' },
        { text: 'Click "Create Token"' },
        { text: 'Give it a name and copy the token' },
        { text: 'For Project ID: go to your project page → Settings' },
      ],
      he: [
        { text: 'היכנסו ל-expo.dev והתחברו' },
        { text: 'לחצו על האווטאר → Access Tokens' },
        { text: 'לחצו "Create Token"' },
        { text: 'תנו שם והעתיקו את הטוקן' },
        { text: 'ל-Project ID: לכו לדף הפרויקט → Settings' },
      ],
    },
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    nameHe: 'ורסל',
    icon: 'globe',
    category: 'hosting',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Token',
        fieldType: 'SECRET',
        required: true,
        hint: 'Personal access token from account settings',
      },
      {
        label: 'Team ID',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'team_...',
        hint: 'Starts with team_ (for team deployments)',
        validationPattern: '^team_',
      },
    ],
    guide: {
      en: [
        { text: 'Go to vercel.com and log in' },
        { text: 'Click your avatar → Settings' },
        { text: 'Go to "Tokens" tab' },
        { text: 'Click "Create" and set a name + scope' },
        { text: 'Copy the token (only shown once!)' },
      ],
      he: [
        { text: 'היכנסו ל-vercel.com והתחברו' },
        { text: 'לחצו על האווטאר → Settings' },
        { text: 'לכו ללשונית "Tokens"' },
        { text: 'לחצו "Create" והגדירו שם + scope' },
        { text: 'העתיקו את הטוקן (מוצג פעם אחת בלבד!)' },
      ],
    },
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    nameHe: 'סופאבייס',
    icon: 'database',
    category: 'backend',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Project URL',
        fieldType: 'URL',
        required: true,
        placeholder: 'https://abc123.supabase.co',
        hint: 'Your project URL ending with .supabase.co',
        validationPattern: '\\.supabase\\.co$',
      },
      {
        label: 'Anon Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'eyJhbGciOiJIUzI1NiIs...',
        hint: 'Long JWT token (public, safe for client)',
      },
      {
        label: 'Service Role Key',
        fieldType: 'SECRET',
        required: false,
        hint: 'Long JWT token (PRIVATE - server only!)',
      },
    ],
    guide: {
      en: [
        { text: 'Go to supabase.com/dashboard and log in' },
        { text: 'Select your project' },
        { text: 'Go to Settings → API' },
        { text: 'Copy the Project URL' },
        { text: 'Copy the anon/public key' },
        { text: 'If needed, copy the service_role key (keep it secret!)' },
      ],
      he: [
        { text: 'היכנסו ל-supabase.com/dashboard והתחברו' },
        { text: 'בחרו את הפרויקט' },
        { text: 'לכו ל-Settings → API' },
        { text: 'העתיקו את ה-Project URL' },
        { text: 'העתיקו את מפתח ה-anon/public' },
        { text: 'אם צריך, העתיקו את מפתח ה-service_role (שמרו בסוד!)' },
      ],
    },
  },
  {
    slug: 'firebase',
    name: 'Firebase',
    nameHe: 'פיירבייס',
    icon: 'flame',
    category: 'backend',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Key',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'AIzaSy...',
        hint: 'Starts with AIzaSy',
        validationPattern: '^AIzaSy',
      },
      {
        label: 'Project ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'my-app-12345',
      },
      {
        label: 'Service Account JSON',
        fieldType: 'SECRET',
        required: false,
        hint: 'For server-side admin access',
      },
    ],
    guide: {
      en: [
        { text: 'Go to console.firebase.google.com' },
        { text: 'Select your project' },
        { text: 'Click the gear icon → Project settings' },
        { text: 'Under "General", find the Web API Key and Project ID' },
        { text: 'For Service Account: go to Service accounts tab → Generate new key' },
      ],
      he: [
        { text: 'היכנסו ל-console.firebase.google.com' },
        { text: 'בחרו את הפרויקט' },
        { text: 'לחצו על אייקון הגלגל → Project settings' },
        { text: 'תחת "General", מצאו את ה-Web API Key וה-Project ID' },
        { text: 'ל-Service Account: לכו ללשונית Service accounts → Generate new key' },
      ],
    },
  },
  {
    slug: 'aws',
    name: 'AWS',
    nameHe: 'אמזון AWS',
    icon: 'server',
    category: 'cloud',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Access Key ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'AKIA...',
        hint: 'Starts with AKIA, 20 characters',
        validationPattern: '^AKIA[A-Z0-9]{16}$',
      },
      {
        label: 'Secret Access Key',
        fieldType: 'SECRET',
        required: true,
        hint: '40-character string',
      },
      {
        label: 'Region',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'us-east-1',
        hint: 'e.g., us-east-1, eu-west-1',
      },
    ],
    guide: {
      en: [
        { text: 'Go to console.aws.amazon.com and log in' },
        { text: 'Click your username → Security Credentials' },
        { text: 'Under "Access keys", click "Create access key"' },
        { text: 'Copy both the Access Key ID and Secret Access Key' },
        { text: 'The Secret Key is only shown once — save it now!' },
      ],
      he: [
        { text: 'היכנסו ל-console.aws.amazon.com והתחברו' },
        { text: 'לחצו על שם המשתמש → Security Credentials' },
        { text: 'תחת "Access keys", לחצו "Create access key"' },
        { text: 'העתיקו את ה-Access Key ID וה-Secret Access Key' },
        { text: 'ה-Secret Key מוצג רק פעם אחת — שמרו אותו עכשיו!' },
      ],
    },
  },
  {
    slug: 'openai',
    name: 'OpenAI',
    nameHe: 'OpenAI',
    icon: 'cpu',
    category: 'ai',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'API Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'sk-...',
        hint: 'Starts with sk-',
        validationPattern: '^sk-',
      },
      {
        label: 'Organization ID',
        fieldType: 'TEXT',
        required: false,
        placeholder: 'org-...',
        hint: 'Starts with org-',
        validationPattern: '^org-',
      },
    ],
    guide: {
      en: [
        { text: 'Go to platform.openai.com and log in' },
        { text: 'Click your avatar → API keys' },
        { text: 'Click "Create new secret key"' },
        { text: 'Copy the key (only shown once!)' },
        { text: 'For Org ID: go to Settings → Organization' },
      ],
      he: [
        { text: 'היכנסו ל-platform.openai.com והתחברו' },
        { text: 'לחצו על האווטאר → API keys' },
        { text: 'לחצו "Create new secret key"' },
        { text: 'העתיקו את המפתח (מוצג פעם אחת בלבד!)' },
        { text: 'ל-Org ID: לכו ל-Settings → Organization' },
      ],
    },
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    nameHe: 'טוויליו',
    icon: 'phone',
    category: 'messaging',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Account SID',
        fieldType: 'TEXT',
        required: true,
        placeholder: 'AC...',
        hint: 'Starts with AC, 34 characters',
        validationPattern: '^AC[a-f0-9]{32}$',
      },
      {
        label: 'Auth Token',
        fieldType: 'SECRET',
        required: true,
        hint: '32-character hex string',
        validationPattern: '^[a-f0-9]{32}$',
      },
      {
        label: 'Phone Number',
        fieldType: 'TEXT',
        required: false,
        placeholder: '+1234567890',
        hint: 'Your Twilio phone number in E.164 format',
        validationPattern: '^\\+\\d{10,15}$',
      },
    ],
    guide: {
      en: [
        { text: 'Go to console.twilio.com and log in' },
        { text: 'Your Account SID and Auth Token are on the dashboard' },
        { text: 'Copy both values' },
        { text: 'For phone number: go to Phone Numbers → Manage → Active Numbers' },
      ],
      he: [
        { text: 'היכנסו ל-console.twilio.com והתחברו' },
        { text: 'ה-Account SID וה-Auth Token מוצגים בדשבורד' },
        { text: 'העתיקו את שני הערכים' },
        { text: 'למספר טלפון: לכו ל-Phone Numbers → Manage → Active Numbers' },
      ],
    },
  },
  {
    slug: 'supabase-venuekit',
    name: 'Supabase Project (VenueKit)',
    nameHe: 'פרויקט סופאבייס (VenueKit)',
    icon: 'database',
    category: 'backend',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Project URL',
        fieldType: 'URL',
        required: true,
        placeholder: 'https://abc123.supabase.co',
        hint: 'Your Supabase project URL ending with .supabase.co',
        validationPattern: '\\.supabase\\.co$',
      },
      {
        label: 'Anon Key',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'eyJhbGciOiJIUzI1NiIs...',
        hint: 'Public anon key (JWT token, safe for client-side)',
      },
      {
        label: 'Service Role Key',
        fieldType: 'SECRET',
        required: true,
        hint: 'Private service_role key (JWT token, server-side only!)',
      },
    ],
    guide: {
      en: [
        { text: 'Go to supabase.com/dashboard and log in (or create an account)' },
        { text: 'Click "New Project" and choose a name, password, and region' },
        { text: 'Wait for the project to finish provisioning' },
        { text: 'Go to Settings → API in the left sidebar' },
        { text: 'Copy the "Project URL" (e.g., https://abc123.supabase.co)' },
        { text: 'Under "Project API keys", copy the anon/public key' },
        { text: 'Copy the service_role key (keep this secret — never expose in client code!)' },
      ],
      he: [
        { text: 'היכנסו ל-supabase.com/dashboard והתחברו (או צרו חשבון)' },
        { text: 'לחצו "New Project" ובחרו שם, סיסמה ואזור' },
        { text: 'חכו שהפרויקט יסיים להתכונן' },
        { text: 'לכו ל-Settings → API בסרגל הצדדי' },
        { text: 'העתיקו את ה-"Project URL" (למשל: https://abc123.supabase.co)' },
        { text: 'תחת "Project API keys", העתיקו את מפתח ה-anon/public' },
        { text: 'העתיקו את מפתח ה-service_role (שמרו בסוד — לעולם אל תחשפו בקוד צד לקוח!)' },
      ],
    },
  },
  {
    slug: 'google-oauth-web',
    name: 'Google OAuth (Web)',
    nameHe: 'גוגל OAuth (אתר)',
    icon: 'shield',
    category: 'auth',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Client ID',
        fieldType: 'TEXT',
        required: true,
        placeholder: '123456789-abc.apps.googleusercontent.com',
        hint: 'Ends with .apps.googleusercontent.com',
        validationPattern: '\\.apps\\.googleusercontent\\.com$',
      },
      {
        label: 'Client Secret',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'GOCSPX-...',
        hint: 'Starts with GOCSPX-',
        validationPattern: '^GOCSPX-',
      },
    ],
    guide: {
      en: [
        { text: 'Go to console.cloud.google.com and log in' },
        { text: 'Create a new project or select an existing one' },
        { text: 'Go to APIs & Services → OAuth consent screen' },
        { text: 'Configure the consent screen (External, add app name and email)' },
        { text: 'Go to APIs & Services → Credentials' },
        { text: 'Click "Create Credentials" → "OAuth client ID"' },
        { text: 'Choose "Web application" as the type' },
        { text: 'Add your site URL to "Authorized redirect URIs" (e.g., https://abc123.supabase.co/auth/v1/callback)' },
        { text: 'Copy the Client ID and Client Secret' },
      ],
      he: [
        { text: 'היכנסו ל-console.cloud.google.com והתחברו' },
        { text: 'צרו פרויקט חדש או בחרו קיים' },
        { text: 'לכו ל-APIs & Services → OAuth consent screen' },
        { text: 'הגדירו את מסך ההסכמה (External, הוסיפו שם אפליקציה ואימייל)' },
        { text: 'לכו ל-APIs & Services → Credentials' },
        { text: 'לחצו "Create Credentials" → "OAuth client ID"' },
        { text: 'בחרו "Web application" כסוג' },
        { text: 'הוסיפו את כתובת האתר ל-"Authorized redirect URIs" (למשל: https://abc123.supabase.co/auth/v1/callback)' },
        { text: 'העתיקו את ה-Client ID וה-Client Secret' },
      ],
    },
  },
  {
    slug: 'github',
    name: 'GitHub',
    nameHe: 'גיטהאב',
    icon: 'github',
    category: 'development',
    authMethod: 'MANUAL',
    fields: [
      {
        label: 'Personal Access Token',
        fieldType: 'SECRET',
        required: true,
        placeholder: 'ghp_... or github_pat_...',
        hint: 'Fine-grained or classic token',
        validationPattern: '^(ghp_|github_pat_)',
      },
    ],
    guide: {
      en: [
        { text: 'Go to github.com and log in' },
        { text: 'Click your avatar → Settings' },
        { text: 'Go to Developer settings → Personal access tokens' },
        { text: 'Click "Generate new token" (fine-grained recommended)' },
        { text: 'Select permissions and generate' },
        { text: 'Copy the token (only shown once!)' },
      ],
      he: [
        { text: 'היכנסו ל-github.com והתחברו' },
        { text: 'לחצו על האווטאר → Settings' },
        { text: 'לכו ל-Developer settings → Personal access tokens' },
        { text: 'לחצו "Generate new token" (fine-grained מומלץ)' },
        { text: 'בחרו הרשאות וצרו' },
        { text: 'העתיקו את הטוקן (מוצג פעם אחת בלבד!)' },
      ],
    },
  },
];
